name = "DiscreteNumberSystems"
uuid = "6419c2d5-dd4c-4770-b8ca-96aa23ef113e"
authors = ["talonmyburgh <tmyburgh@gmail.com>", "radonnachie <code@radonn.co.za>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
